# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

target 'SinchMultiPeer' do
pod 'SinchRTC', '~> 3.5'
pod 'Parse', '~> 1.7'
end

target 'SinchMultiPeerTests' do

end

